version: '3.7'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass1
      MYSQL_DATABASE: charity_donation
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
